#pragma once

#include "./proto/xseer_db.hpp"
#include "./proto/xseer_db_enum.hpp"
#include "./proto/xseer_online.hpp"
#include "./proto/xseer_online_enum.hpp"
#include "./proto/xseer_redis.hpp"
#include "./proto/xseer_redis_enum.hpp"
#include "./proto/common.hpp"

#include "global_data.hpp"
#include "utils.hpp"
#include "battle.hpp"
#include "instance.hpp"
#include "restriction.hpp"
#include "achievement.hpp"
#include "adventure.hpp"
#include "arena.hpp"
#include "player.hpp"
#include "dbroute.hpp"
#include "hero.hpp"
#include "soldier.hpp"
#include "equipment.hpp"
#include "btl_soul.hpp"
#include "astrology.hpp"
#include "general.hpp"
#include "item.hpp"
#include "guild.hpp"
#include "horse.hpp"
#include "internal_affairs.hpp"
#include "log_thread.hpp"
#include "lua_log.hpp"
#include "lua_script_manage.hpp"
#include "login.hpp"
#include "stat_log.hpp"
#include "trial_tower.hpp"
#include "redis.hpp"
#include "wheel_timer.h"
#include "hash.hpp"
#include "cli_dispatch.hpp"
#include "timer.hpp"
#include "shop.hpp"
#include "skill.hpp"
#include "soldier.hpp"
#include "talent.hpp"
#include "task.hpp"
#include "ten_even_draw.hpp"
#include "treasure_risk.hpp"
#include "trial_tower.hpp"
#include "vip.hpp"


extern "C" {
#include <math.h>
}

